language: ruby
sudo: false
cache:
  - bundler
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck
script: bundle exec rake test
rvm:
  - 1.9.3
  - 2.0
  - 2.1
gemfile:
  - Gemfile
  - gemfiles/chef-11.4.4/Gemfile
  - gemfiles/chef-11.6.2/Gemfile
  - gemfiles/chef-11.8.2/Gemfile
  - gemfiles/chef-11.10.4/Gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/chef-11.4.4/Gemfile
    - rvm: 2.1
      gemfile: gemfiles/chef-11.4.4/Gemfile
    - rvm: 2.0
      gemfile: gemfiles/chef-11.6.2/Gemfile
    - rvm: 2.1
      gemfile: gemfiles/chef-11.6.2/Gemfile
    - rvm: 2.0
      gemfile: gemfiles/chef-11.8.2/Gemfile
    - rvm: 2.1
      gemfile: gemfiles/chef-11.8.2/Gemfile
    - rvm: 2.0
      gemfile: gemfiles/chef-11.10.4/Gemfile
    - rvm: 2.1
      gemfile: gemfiles/chef-11.10.4/Gemfile
  allow_failures:
    - gemfile: gemfiles/chef-11.4.4/Gemfile
